const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Injects a `release` signing config into the generated android/app/build.gradle.
 *
 * - If the Gradle properties MYAPP_RELEASE_STORE_FILE / _STORE_PASSWORD /
 *   _KEY_ALIAS / _KEY_PASSWORD are present at build time, the release APK is
 *   signed with that keystore (set them in android/gradle.properties or via -P).
 * - Otherwise it falls back to the Expo-generated debug keystore, which is fine
 *   for personal sideloading.
 *
 * Because android/ is gitignored and regenerated by `expo prebuild`, this has to
 * be applied as a config plugin rather than a manual build.gradle edit.
 */
const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            } else {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
`;

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    let contents = mod.modResults.contents;

    if (!contents.includes('MYAPP_RELEASE_STORE_FILE')) {
      // Add a `release` signing config right after the `debug` one.
      const withRelease = contents.replace(
        /(signingConfigs\s*\{\s*\n\s*debug\s*\{[\s\S]*?\n {8}\}\n)/,
        `$1${RELEASE_SIGNING_CONFIG}`,
      );

      // Only repoint the release build type if the signing config was actually
      // inserted — otherwise leave the safe debug-signing default in place.
      if (withRelease.includes('MYAPP_RELEASE_STORE_FILE')) {
        contents = withRelease.replace(
          /(release\s*\{\s*\n(?:\s*\/\/.*\n)*\s*)signingConfig signingConfigs\.debug/,
          '$1signingConfig signingConfigs.release',
        );
      } else {
        console.warn(
          '[withReleaseSigning] could not locate signingConfigs.debug block; ' +
            'release build will use the default debug signing config.',
        );
      }
    }

    mod.modResults.contents = contents;
    return mod;
  });
}

module.exports = withReleaseSigning;
